### PR TITLE
Windows duckdb.dll export symbols

### PR DESCRIPTION
**Pull request by chilarai**
Pull request for more exported DuckDB symbols with duckdb.dll for Windows

### CODE REVIEW

**Comment by chilarai** [comment]
Need a little help with Python here. In the **Python 3 Windows** build step,  I am getting this error
```sh
Error: Command ['pip', 'wheel', 'D:\\a\\duckdb\\duckdb\\tools\\pythonpkg\\duckdb_tarball', '-w', 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\cibuildwheelnscshzgu\\built_wheel', '--no-deps'] failed with code 1. None
Error: Process completed with exit code 1.
```

Apparently, Python build process is unable to parse the CMakeLists.txt file where I have mentioned `add_definitions(-DDUCKDB_BUILD_LIBRARY)` and throwing `unresolved external symbol "__declspec(dllimport)`

Now, I don't know how to resolve this error.

**Comment by Mytherin** [comment]
Thanks for the PR! This is looking much better already. Indeed the Python client does not use cmake; it has its own build process. I think you can resolve this by adding this to `tools/pythonpkg/setup.py` (on e.g. line 57):

```python
toolchain_args.extend(['-DDUCKDB_BUILD_LIBRARY'])
```

We probably need the same in `tools/rpkg/rconfigure.py` (on e.g. line 20):

```python
extension_list += " -DDUCKDB_BUILD_LIBRARY"
```

**Comment by chilarai** [comment]
Thanks. I have updated

**Comment by Mytherin** [comment]
Can you merge with the master? After that is done and all the tests pass I think we can merge this in.

**Pull request closed without merging**
